name: mydocker

services:
  windows11l:
    image: dockurr/windows
    container_name: docker-windows11l
    environment:
      VERSION: "11l"
      RAW_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "32G"
      USERNAME: "de.lk"
      PASSWORD: "123"
      LANGUAGE: "English"
      REGION: "en-US"
      KEYBOARD: "en-US"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: unless-stopped