[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :1 -screen 0 1600x900x24
autorestart=true

[program:xfce]
command=dbus-launch --exit-with-session startxfce4
environment=DISPLAY=":1"
autorestart=true

[program:x11vnc]
command=x11vnc -display :1 -forever -shared -nopw
autorestart=true

[program:novnc]
command=/opt/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autorestart=true